### ISSUE TITLE
Shopify now Supports Feature Image

### ISSUE THREAD

**Issue by suture** [Twigs-for-Timber/news-with-feature-images-and-videos#1]
Hi Cam
https://docs.shopify.com/themes/liquid-documentation/objects/article#article-image

Featured images on a blog post are now a feature in Shopify. You will see a place in the blog admin to put an image and they can be access in the theme with:

{{ article.image }}

**Comment by cam** [comment]
Thanks for pointing that out! I hadn't noticed that one. I'll add support for that as part of the matrix for finding images :)

**Comment by cam** [comment]
Latest version now has support for this too :) 3 levels of options: article.image, inline image or video.
